"""
Brand templates for VIP Medical Group location content generator.
Each brand has its own template for Open and Coming Soon page types.
AI fills in: neighborhoods, directions description, local context.
"""

# ── Shared field sets ──────────────────────────────────────────────────────────

_REGIONAL_VEIN_TREATMENTS = [
    "Sclerotherapy",
    "Radiofrequency Ablation (RFA)",
    "Laser vein treatment",
    "Spider vein removal",
]

_REGIONAL_VEIN_CONDITIONS = [
    "Varicose veins",
    "Spider veins",
    "Venous insufficiency",
    "Leg pain",
]

# ── Brand definitions ──────────────────────────────────────────────────────────

BRANDS = {
    # ───── Main brands ─────
    "vip": {
        "name": "VIP Medical Group",
        "domain": "vipmedicalgroup.com",
        "phone": "844-297-2300",
        "specialty": "vein_pain",
        "language": "en",
        "type": "main",
        "group": "VIP Medical Group",
        "order": 1,
        "treatments": [
            "Sclerotherapy for spider veins",
            "Radiofrequency Ablation (RFA)",
            "Endovenous Laser Treatment (EVLT)",
            "Pain management consultations",
            "Minimally invasive spine treatments",
        ],
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Chronic venous insufficiency",
            "Back pain",
            "Spine conditions",
        ],
        "trust_points": [
            "Ivy League-trained, board-certified specialists",
            "Comprehensive vein and pain care under one roof",
            "Most insurances accepted",
            "Minimally invasive, outpatient procedures",
            "Convenient locations across the Northeast and beyond",
        ],
    },
    "vtc": {
        "name": "VTC - Vein Treatment Clinic",
        "domain": "veintreatmentclinic.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "main",
        "group": "VTC",
        "order": 2,
        "treatments": [
            "Ultrasound-guided sclerotherapy",
            "Radiofrequency Ablation (RFA)",
            "Endovenous Laser Treatment (EVLT)",
            "Ambulatory phlebectomy",
            "Spider vein sclerotherapy",
        ],
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Chronic venous insufficiency",
            "Leg swelling and heaviness",
            "Leg pain and cramping",
        ],
        "trust_points": [
            "Ivy League-trained, board-certified vein specialists",
            "Minimally invasive, outpatient procedures",
            "Most insurances accepted — we verify coverage for you",
            "State-of-the-art facilities and diagnostic technology",
            "Compassionate, patient-centered care",
        ],
    },
    "pts": {
        "name": "Pain Treatment Specialists",
        "domain": "paintreatmentspecialists.com",
        "phone": "844-597-0492",
        "specialty": "pain",
        "language": "en",
        "type": "main",
        "group": "PTS",
        "order": 3,
        "treatments": [
            "Epidural steroid injections",
            "Nerve block procedures",
            "Minimally invasive spine treatments",
            "Radiofrequency ablation for pain",
            "Facet joint injections",
        ],
        "conditions": [
            "Chronic back pain",
            "Sciatica",
            "Spine conditions",
            "Joint pain",
            "Nerve pain",
        ],
        "trust_points": [
            "Harvard-trained, fellowship-certified pain specialists",
            "Non-surgical, minimally invasive approach",
            "Most insurances accepted",
            "State-of-the-art pain management techniques",
            "Personalized treatment plans",
        ],
    },

    # ───── Vein Treatment group ─────
    "veintreatment": {
        "name": "Vein Treatment",
        "domain": "veintreatment.com",
        "phone": "(855) 699-2004",
        "specialty": "vein",
        "language": "en",
        "type": "microsite",
        "group": "Vein Treatment",
        "order": 10,
        "treatments": [
            "Sclerotherapy",
            "Radiofrequency Ablation (RFA)",
            "Endovenous Laser Treatment (EVLT)",
            "Ambulatory phlebectomy",
            "Ultrasound-guided vein mapping",
        ],
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Chronic venous insufficiency",
            "Leg heaviness",
            "Vein disease",
        ],
        "trust_points": [
            "Board-certified vein specialists",
            "Minimally invasive, same-day treatments",
            "Insurance coverage verified",
            "Modern facilities and equipment",
            "Expert diagnosis and personalized care",
        ],
    },
    "veintreatmenttx": {
        "name": "Vein Treatment TX",
        "domain": "veintreatmenttx.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Texas",
        "group": "Vein Treatment",
        "order": 11,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified Texas vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Texas locations",
        ],
    },
    "veintreatmentca": {
        "name": "Vein Treatment CA",
        "domain": "veintreatmentca.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "California",
        "group": "Vein Treatment",
        "order": 12,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified California vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient California locations",
        ],
    },
    "veintreatmentli": {
        "name": "Vein Treatment Long Island",
        "domain": "veintreatmentli.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Long Island, New York",
        "group": "Vein Treatment",
        "order": 13,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified Long Island vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Long Island locations",
        ],
    },
    "veintreatmentsmd": {
        "name": "Vein Treatment MD",
        "domain": "veintreatmentsmd.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Maryland",
        "group": "Vein Treatment",
        "order": 14,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified Maryland vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Maryland locations",
        ],
    },
    "veintreatmentnj": {
        "name": "Vein Treatment NJ",
        "domain": "veintreatmentnj.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "New Jersey",
        "group": "Vein Treatment",
        "order": 15,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified New Jersey vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient New Jersey locations",
        ],
    },
    "veintreatmentnyc": {
        "name": "Vein Treatment NYC",
        "domain": "veintreatmentnyc.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "New York City",
        "group": "Vein Treatment",
        "order": 16,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified NYC vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient New York City locations",
        ],
    },
    "veintreatmentsd": {
        "name": "Vein Treatment San Diego",
        "domain": "veintreatmentsd.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "San Diego, California",
        "group": "Vein Treatment",
        "order": 17,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified San Diego vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient San Diego locations",
        ],
    },
    "veintreatmentsct": {
        "name": "Vein Treatment CT",
        "domain": "veintreatmentsct.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Connecticut",
        "group": "Vein Treatment",
        "order": 18,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Board-certified Connecticut vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Connecticut locations",
        ],
    },

    # ───── Vein Centers group ─────
    "veincentersca": {
        "name": "Vein Centers CA",
        "domain": "veincentersca.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "California",
        "group": "Vein Centers",
        "order": 20,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "California's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient California locations",
        ],
    },
    "veincentersct": {
        "name": "Vein Centers CT",
        "domain": "veincentersct.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Connecticut",
        "group": "Vein Centers",
        "order": 21,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "Connecticut's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Connecticut locations",
        ],
    },
    "veincentersli": {
        "name": "Vein Centers Long Island",
        "domain": "veincentersli.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Long Island, New York",
        "group": "Vein Centers",
        "order": 22,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "Long Island's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Long Island locations",
        ],
    },
    "veincentersmd": {
        "name": "Vein Centers MD",
        "domain": "veincentersmd.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Maryland",
        "group": "Vein Centers",
        "order": 23,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "Maryland's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Maryland locations",
        ],
    },
    "veincentersnj": {
        "name": "Vein Centers NJ",
        "domain": "veincentersnj.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "New Jersey",
        "group": "Vein Centers",
        "order": 24,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "New Jersey's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient New Jersey locations",
        ],
    },
    "veincentersny": {
        "name": "Vein Centers NY",
        "domain": "veincentersny.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "New York",
        "group": "Vein Centers",
        "order": 25,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "New York's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient New York locations",
        ],
    },
    "veincenterstx": {
        "name": "Vein Centers TX",
        "domain": "veincenterstx.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Texas",
        "group": "Vein Centers",
        "order": 26,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "Texas's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Texas locations",
        ],
    },
    "paveincenters": {
        "name": "PA Vein Centers",
        "domain": "paveincenters.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Pennsylvania",
        "group": "Vein Centers",
        "order": 27,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg swelling",
        ],
        "trust_points": [
            "Pennsylvania's trusted vein specialists",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Pennsylvania locations",
        ],
    },

    # ───── Vein Clinics group ─────
    "veincliniclongisland": {
        "name": "Vein Clinic Long Island",
        "domain": "veincliniclongisland.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Long Island, New York",
        "group": "Vein Clinics",
        "order": 30,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Venous insufficiency",
            "Leg heaviness",
        ],
        "trust_points": [
            "Long Island's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Long Island locations",
        ],
    },
    "veinclinicsca": {
        "name": "Vein Clinics CA",
        "domain": "veinclinicsca.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "California",
        "group": "Vein Clinics",
        "order": 31,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "California's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient California clinic locations",
        ],
    },
    "veinclinicsct": {
        "name": "Vein Clinics CT",
        "domain": "veinclinicsct.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Connecticut",
        "group": "Vein Clinics",
        "order": 32,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Connecticut's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Connecticut clinic locations",
        ],
    },
    "veinclinicsmd": {
        "name": "Vein Clinics MD",
        "domain": "veinclinicsmd.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Maryland",
        "group": "Vein Clinics",
        "order": 33,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Maryland's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Maryland clinic locations",
        ],
    },
    "veinclinicsnj": {
        "name": "Vein Clinics NJ",
        "domain": "veinclinicsnj.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "New Jersey",
        "group": "Vein Clinics",
        "order": 34,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "New Jersey's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient New Jersey clinic locations",
        ],
    },
    "veinclinicsny": {
        "name": "Vein Clinics NY",
        "domain": "veinclinicsny.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "New York",
        "group": "Vein Clinics",
        "order": 35,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "New York's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient New York clinic locations",
        ],
    },
    "paveinclinics": {
        "name": "PA Vein Clinics",
        "domain": "paveinclinics.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "regional",
        "region": "Pennsylvania",
        "group": "Vein Clinics",
        "order": 36,
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Pennsylvania's leading vein clinics",
            "Minimally invasive treatments",
            "Insurance accepted",
            "Convenient Pennsylvania clinic locations",
        ],
    },

    # ───── Other ─────
    "veindoctor": {
        "name": "Vein Doctor",
        "domain": "veindoctor.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "en",
        "type": "other",
        "group": "Other",
        "order": 40,
        "url_pattern": "/{state}/{city}/",
        "treatments": _REGIONAL_VEIN_TREATMENTS,
        "conditions": _REGIONAL_VEIN_CONDITIONS,
        "trust_points": [
            "Find a top-rated vein doctor near you",
            "Board-certified vein specialists",
            "Minimally invasive, same-day procedures",
            "Insurance accepted and verified",
            "Personalized vein care plans",
        ],
    },
    "venasvarices": {
        "name": "Venas Varices",
        "domain": "venasvarices.com",
        "phone": "(844) 690-1788",
        "specialty": "vein",
        "language": "es",
        "type": "microsite",
        "group": "Other",
        "order": 41,
        "treatments": [
            "Escleroterapia guiada por ultrasonido",
            "Ablación por radiofrecuencia (RFA)",
            "Tratamiento láser endovenoso (EVLT)",
            "Flebectomía ambulatoria",
            "Escleroterapia para arañas vasculares",
        ],
        "conditions": [
            "Várices",
            "Arañas vasculares (telangiectasias)",
            "Insuficiencia venosa crónica",
            "Hinchazón y pesadez en las piernas",
            "Dolor y calambres en las piernas",
        ],
        "trust_points": [
            "Especialistas certificados formados en universidades de élite",
            "Procedimientos mínimamente invasivos y ambulatorios",
            "Aceptamos la mayoría de los seguros médicos",
            "Tecnología de diagnóstico de vanguardia",
            "Atención personalizada y compasiva",
        ],
    },
    "legulcercenter": {
        "name": "Leg Ulcer Center",
        "domain": "legulcercenter.com",
        "phone": "(877) 687-0898",
        "specialty": "vein",
        "language": "en",
        "type": "other",
        "group": "Other",
        "order": 42,
        "url_pattern": "/locations/{state}/{city}/",
        "treatments": [
            "Sclerotherapy",
            "Radiofrequency Ablation (RFA)",
            "Ultrasound-guided vein mapping",
            "Spider vein treatment",
        ],
        "conditions": [
            "Varicose veins",
            "Spider veins",
            "Chronic venous insufficiency",
            "Venous leg ulcers",
            "Leg swelling and heaviness",
        ],
        "trust_points": [
            "Harvard-trained leadership team with collaborative care approach",
            "Minimally invasive, zero-downtime procedures",
            "Most major insurances accepted, including Medicare",
            "5-star ratings across Google, Facebook, and RealSelf",
            "State-of-the-art facilities with cutting-edge technology",
            "Free insurance verification before treatment",
        ],
    },
}


def get_brand(brand_id: str) -> dict:
    """Get brand config by ID."""
    return BRANDS.get(brand_id)


def list_brands() -> list:
    """List all brands with basic info, sorted by order."""
    items = [
        {
            "id": k,
            "name": v["name"],
            "domain": v["domain"],
            "type": v["type"],
            "language": v.get("language", "en"),
            "group": v.get("group", "Other"),
            "order": v.get("order", 99),
        }
        for k, v in BRANDS.items()
    ]
    items.sort(key=lambda x: x["order"])
    return items
